# $CHART_UID & $CHART_GID need to be replaced with actual values
# PROJECT=$(oc project -q)
#
# CHART_UID=$(oc get project ${PROJECT} -o jsonpath="{['metadata.annotations.openshift\.io/sa\.scc\.uid-range']}" | sed "s@/.*@@")
# CHART_GID=$(oc get project ${PROJECT} -o jsonpath="{['metadata.annotations.openshift\.io/sa\.scc\.supplemental-groups']}" | sed "s@/.*@@")

# uid: $CHART_UID
# gid: $CHART_GID

scheduler:
  replicas: 2

webserver:
  replicas: 2

statsd:
  uid: null

# redis:
#   securityContext:
#     runAsUser: $CHART_UID

executor: KubernetesExecutor
fernetKey: "7T512UXSSmBOkpWimFHIVb8jK6lfmSAvx4mO6Arehnc="
webserverSecretKey: "AvoidingDialogs"


dags:
  gitSync:
    enabled: true
    # repo: https://github.com/redhat-na-ssa/airflow-on-openshift.git
    # branch: main
    # subPath: example_dag
    uid: null

postgresql:
  primary:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false

# ingress:
#   web:
#     enabled: true
